// Definicion de los pasos y campos del wizard (ver docs/03-formulario.md).
// Fuente unica de verdad para render y validacion.
import type { FormData, Opcion, StepDef } from "./types.js";

export const FAMILIAS: Opcion[] = [
  { value: "servicios_profesionales", label: "Servicios profesionales" },
  { value: "gastronomia", label: "Gastronomía" },
  { value: "comercio_minorista", label: "Comercio minorista" },
  { value: "mayorista_distribucion", label: "Mayorista / distribución" },
  { value: "industria_manufactura", label: "Industria / manufactura" },
  { value: "salud_bienestar", label: "Salud y bienestar" },
  { value: "tecnologia_digital", label: "Tecnología / digital" },
  { value: "ecommerce", label: "E-commerce" },
  { value: "logistica_transporte", label: "Logística / transporte" },
  { value: "construccion", label: "Construcción / obra" },
  { value: "educacion", label: "Educación" },
  { value: "belleza_estetica_fitness", label: "Belleza / estética / fitness" },
  { value: "agro", label: "Agro / producción primaria" },
  { value: "turismo_hoteleria", label: "Turismo / hotelería" },
  { value: "inmobiliario_rentas", label: "Inmobiliario / rentas" },
  { value: "otros", label: "Otro" },
];

export const PROVINCIAS: Opcion[] = [
  "Buenos Aires", "CABA", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes",
  "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones",
  "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe",
  "Santiago del Estero", "Tierra del Fuego", "Tucumán",
].map((p) => ({ value: p, label: p }));

const stockFamilias = new Set([
  "gastronomia", "comercio_minorista", "mayorista_distribucion", "industria_manufactura",
  "ecommerce", "agro", "salud_bienestar", "construccion", "belleza_estetica_fitness", "otros",
]);
export function familiaTieneStock(data: FormData): boolean {
  return stockFamilias.has(String(data.familia ?? ""));
}

// --- Pasos del wizard (W1..W7). La elegibilidad (S5) se maneja aparte. ---
export const STEPS: StepDef[] = [
  {
    id: "w1",
    titulo: "Tu negocio",
    descripcion: "Contanos qué hacés y dónde.",
    fields: [
      { id: "actividadDesc", label: "¿Qué hace tu empresa?", type: "textarea", required: true,
        help: "Se usa (editable) en tu publicación.", ejemplo: "Panadería y cafetería de barrio con venta al público y delivery", min: 30 },
      { id: "provincia", label: "Provincia", type: "select", required: true, opciones: PROVINCIAS },
      { id: "localidad", label: "Localidad", type: "text", required: true, ejemplo: "Villa Carlos Paz" },
      { id: "anioInicio", label: "¿En qué año empezó a operar?", type: "int", required: true, min: 1900, max: 2026, ejemplo: "2018" },
      { id: "formaJuridica", label: "Forma jurídica", type: "select",
        opciones: ["Unipersonal", "Monotributo", "SRL", "SA", "SAS", "Otra"].map((v) => ({ value: v, label: v })) },
      { id: "empleados", label: "¿Cuántos empleados tenés (sin contar dueños)?", type: "int", required: true, min: 0, ejemplo: "8" },
      { id: "duenosTrabajan", label: "¿Cuántos dueños trabajan en el negocio?", type: "int", required: true, min: 0, ejemplo: "2" },
      { id: "local", label: "El local donde operás es…", type: "select", required: true,
        opciones: [{ value: "propio", label: "Propio" }, { value: "alquilado", label: "Alquilado" }, { value: "na", label: "No aplica" }] },
    ],
  },
  {
    id: "w2",
    titulo: "Ventas",
    descripcion: "Cuánto vendés hoy.",
    fields: [
      { id: "monedaCarga", label: "¿En qué moneda cargás los números?", type: "select", required: true,
        opciones: [{ value: "ARS", label: "Pesos (ARS)" }, { value: "USD", label: "Dólares (USD)" }] },
      { id: "ventasCargaModo", label: "¿Cómo querés cargar tus ventas?", type: "select", required: true,
        opciones: [{ value: "anual", label: "Total anual" }, { value: "promedio", label: "Promedio de un mes típico" }] },
      { id: "ventasAnual", label: "Ventas de los últimos 12 meses", type: "money", required: true,
        help: "Facturación total, sin IVA.", ejemplo: "240.000.000", showIf: (d) => d.ventasCargaModo !== "promedio" },
      { id: "ventasProm", label: "Ventas de un mes típico", type: "money", required: true,
        help: "Se multiplica por 12.", showIf: (d) => d.ventasCargaModo === "promedio" },
      { id: "anioRepresentativo", label: "¿El último año fue \"normal\"?", type: "select", required: true,
        opciones: [{ value: "normal", label: "Sí, fue normal" }, { value: "mejor", label: "Fue mejor de lo normal" }, { value: "peor", label: "Fue peor de lo normal" }] },
      { id: "estacional", label: "¿Tus ventas se concentran en ciertos meses?", type: "bool" },
      { id: "mesesFuertes", label: "¿Qué meses o fechas concentran las ventas?", type: "text",
        help: "Ej: diciembre y fiestas, verano, marzo (vuelta a clases). Opcional.",
        showIf: (d) => d.estacional === true },
      { id: "tipoCliente", label: "¿A quién le vendés principalmente?", type: "select",
        opciones: [
          { value: "consumidor", label: "Consumidor final (B2C)" },
          { value: "empresas", label: "Otras empresas (B2B)" },
          { value: "mixto", label: "Mixto" },
        ] },
      { id: "concentracionClientePct", label: "¿Qué % de las ventas hace tu cliente más grande?", type: "percent",
        help: "Mucha concentración = más riesgo. Si le vendés a muchos clientes chicos, poné un número bajo.", ejemplo: "15" },
    ],
  },
  {
    id: "w3",
    titulo: "Costos y gastos",
    descripcion: "Cuánto te cuesta operar. No incluyas lo que retirás como dueño (eso va en el paso siguiente).",
    fields: [
      { id: "cogsModo", label: "¿Cómo cargás el costo de lo que vendés?", type: "select", required: true,
        help: "Es lo que te cuesta la mercadería o los insumos que vendés (SIN sueldos, alquiler ni otros gastos fijos).",
        opciones: [{ value: "pct", label: "Como % de las ventas" }, { value: "monto", label: "Como monto anual" }] },
      { id: "cogsPct", label: "Costo de mercadería / insumos (% de ventas)", type: "percent", required: true,
        help: "Ejemplo: si vendés un producto a $100 y comprarlo/producirlo te cuesta $40, poné 40%.", ejemplo: "40", showIf: (d) => d.cogsModo !== "monto" },
      { id: "cogsMonto", label: "Costo de mercadería / insumos (monto anual)", type: "money", required: true,
        help: "Cuánto gastaste en el año en comprar/producir lo que vendiste. Ej: si vendiste $100M y la mercadería te costó $40M, poné 40.000.000.",
        showIf: (d) => d.cogsModo === "monto" },
      { id: "gAlquiler", label: "Alquiler del local", type: "moneyPeriod",
        showIf: (d) => d.local === "alquilado", help: "Solo si el local es alquilado." },
      { id: "gSueldos", label: "Sueldos de empleados (con cargas)", type: "moneyPeriod",
        help: "No incluyas a los dueños." },
      { id: "gServicios", label: "Servicios (luz, gas, internet, teléfono)", type: "moneyPeriod" },
      { id: "gLogistica", label: "Logística, fletes, combustible", type: "moneyPeriod" },
      { id: "gPublicidad", label: "Publicidad y marketing", type: "moneyPeriod" },
      { id: "gComisiones", label: "Comisiones (tarjetas, plataformas, vendedores)", type: "moneyPeriod" },
      { id: "gImpuestos", label: "Impuestos y tasas (IIBB, municipal)", type: "moneyPeriod" },
      { id: "gOtros", label: "Otros gastos", type: "moneyPeriod" },
    ],
  },
  {
    id: "w4",
    titulo: "Tu sueldo y ajustes",
    descripcion: "Ajustamos el resultado para reflejar lo que realmente gana el negocio.",
    fields: [
      { id: "retiroDuenos", label: "¿Cuánto retiran EN TOTAL todos los dueños que trabajan?", type: "moneyPeriod", required: true,
        help: "Sumá los sueldos y retiros de TODOS los dueños que trabajan en el negocio (no de uno solo)." },
      { id: "sueldoMercadoDueno", label: "Si tuvieras que contratar empleados para reemplazar a los dueños que trabajan, ¿cuánto pagarías EN TOTAL?", type: "moneyPeriod", required: true,
        help: "El costo de mercado de reemplazar a TODOS los dueños que trabajan (no a uno). Ej: si trabajan 2 dueños, sumá los 2 sueldos que pagarías. Sirve para saber cuánto gana el negocio más allá del trabajo de los dueños." },
      { id: "gastosPersonales", label: "Gastos personales tuyos que pagás con la empresa (al año)", type: "money",
        help: "Auto particular, celular, viajes personales, etc. que hoy figuran como gasto de la empresa. Los volvemos a sumar a la ganancia porque no son costos reales del negocio: los estarías 'inflando' como gasto.", ejemplo: "3.000.000" },
      { id: "extraordGasto", label: "Gastos por única vez en el último año", type: "money",
        help: "Gastos que no se repiten (juicio, mudanza, una reparación grande). Los sumamos de vuelta porque no son parte del funcionamiento normal." },
      { id: "extraordIngreso", label: "Ingresos por única vez en el último año", type: "money",
        help: "Ingresos que no se repiten (venta de una máquina, un reintegro, una indemnización cobrada). Los restamos para no contar como ganancia habitual algo que no se va a repetir." },
    ],
  },
  {
    id: "w5",
    titulo: "Activos",
    descripcion: "Qué se lleva el comprador con la empresa.",
    fields: [
      { id: "inventario", label: "Valor de tu stock / mercadería hoy", type: "money",
        showIf: familiaTieneStock, help: "A precio de costo." },
      { id: "inventarioMinimo", label: "Stock mínimo para que el negocio funcione", type: "money",
        showIf: familiaTieneStock, help: "Capital de trabajo básico." },
      { id: "porCobrar", label: "¿Cuánto te deben tus clientes hoy?", type: "money" },
      { id: "porPagar", label: "¿Cuánto les debés a proveedores hoy?", type: "money" },
      { id: "equipamiento", label: "Valor de equipos, maquinaria, herramientas, rodados", type: "money",
        help: "A valor de usado / mercado.", ejemplo: "20.000.000" },
      { id: "equipamientoDetalle", label: "¿Qué incluye ese equipamiento?", type: "multiselect",
        help: "Marcá lo que corresponda. Opcional.",
        opciones: ["Maquinaria", "Rodados / vehículos", "Herramientas", "Muebles e instalaciones", "Equipos informáticos / tecnología", "Otros"].map((v) => ({ value: v, label: v })),
        showIf: (d) => Number(d.equipamiento) > 0 },
      { id: "inmuebleIncluido", label: "¿El inmueble propio se incluye en la venta?", type: "bool",
        showIf: (d) => d.local === "propio" },
      { id: "inmuebleValor", label: "Valor estimado del inmueble", type: "money",
        showIf: (d) => d.local === "propio" && d.inmuebleIncluido === true },
      { id: "incluyeVenta", label: "¿Qué se incluye en la venta?", type: "multiselect",
        opciones: ["Fondo de comercio", "Stock", "Equipos", "Inmueble", "Marca", "Cartera de clientes", "Empleados", "Intangibles digitales"].map((v) => ({ value: v, label: v })) },
      { id: "intangibles", label: "¿Qué intangibles se llevan con la empresa?", type: "multiselect",
        opciones: ["Marca registrada", "Página web", "Redes sociales", "Cartera de clientes", "Base de datos", "Recetas / procesos", "Licencias / habilitaciones", "Contratos vigentes"].map((v) => ({ value: v, label: v })) },
    ],
  },
  {
    id: "w6",
    titulo: "Deudas",
    descripcion: "Qué debe la empresa hoy.",
    fields: [
      { id: "deudaFinanciera", label: "Deudas con bancos o préstamos", type: "money" },
      { id: "deudaOtros", label: "Otras deudas (proveedores atrasados, AFIP)", type: "money" },
      { id: "contingencias", label: "Juicios o contingencias (monto estimado)", type: "money" },
      { id: "deudaTransfiere", label: "Las deudas, ¿las asume el comprador o quedan con vos?", type: "select", required: true,
        opciones: [{ value: "quedan", label: "Quedan con el dueño" }, { value: "transfieren", label: "Se transfieren al comprador" }] },
    ],
  },
  {
    id: "w7",
    titulo: "Perspectivas",
    descripcion: "Hacia dónde va tu negocio.",
    fields: [
      { id: "tendencia", label: "Mirando para adelante, tu negocio…", type: "select", required: true,
        opciones: [{ value: "crece", label: "Va a crecer" }, { value: "estable", label: "Se mantiene" }, { value: "baja", label: "Va a bajar" }] },
      { id: "crecimientoPct", label: "¿Cuánto esperás crecer por año, en volumen real? (en %, sin contar inflación)", type: "percent",
        help: "Cuánto crecerían las ventas en cantidad/valor real, más allá de la suba de precios. Ej: si esperás vender 5% más por año, poné 5. Opcional.", min: -50, max: 100 },
      { id: "crecimientoMotivo", label: "¿Por qué esperás ese crecimiento?", type: "text",
        help: "Ej: nuevos clientes, apertura de otra sucursal, nuevos productos, mejora de la zona. Opcional.",
        showIf: (d) => d.tendencia === "crece" || (Number(d.crecimientoPct) > 0) },
      { id: "dependenciaDueno", label: "Si el dueño se va, el negocio…", type: "select", required: true,
        opciones: [{ value: "baja", label: "Sigue igual" }, { value: "media", label: "Se complica un poco" }, { value: "alta", label: "Depende mucho de él" }] },
      { id: "dependenciaDetalle", label: "¿Qué tareas clave hace hoy el dueño que un comprador debería cubrir?", type: "textarea",
        help: "Ej: atiende a los clientes principales, maneja proveedores, controla la producción, lleva las cuentas. Opcional, pero ayuda a mostrar qué necesita saber el comprador." },
      { id: "recurrencia", label: "¿Tenés ventas recurrentes o contratos fijos?", type: "bool" },
      { id: "requiereInversion", label: "¿El negocio necesita una inversión importante el próximo año para seguir funcionando?", type: "bool",
        help: "Ej: renovar una máquina clave, refacción del local, cambiar rodados." },
      { id: "inversionMonto", label: "¿De cuánto sería esa inversión, aproximadamente?", type: "money",
        showIf: (d) => d.requiereInversion === true },
      { id: "inversionDetalle", label: "¿En qué?", type: "text",
        help: "Opcional.", showIf: (d) => d.requiereInversion === true },
      { id: "motivoVenta", label: "¿Por qué querés vender?", type: "select", required: true,
        opciones: ["Retiro", "Nuevo proyecto", "Salud", "Mudanza", "Sociedad", "Bajó la rentabilidad", "Otro"].map((v) => ({ value: v, label: v })) },
      { id: "urgencia", label: "¿Con qué urgencia querés vender?", type: "select",
        opciones: [{ value: "sin_apuro", label: "Sin apuro" }, { value: "6_meses", label: "En 6 meses" }, { value: "urgente", label: "Lo antes posible" }] },
    ],
  },
];

export function stepById(id: string): StepDef | undefined {
  return STEPS.find((s) => s.id === id);
}
